/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 * Formulario que permite seleccionar un objeto para manipular (ya sean productos, 
 * empresas o usuarios) interactuando con el nombre para posteriormente acceder a 
 * ellos por medio de una funcion de ubicacion de la posicion en el respectivo arreglo
 * @author Andrés Morales
 */
public class Auxiliar extends javax.swing.JFrame {

    /**
     * Creates new form Auxiliar
     */
    public Auxiliar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cobProd = new javax.swing.JComboBox<>();
        botAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 180));
        getContentPane().setLayout(null);

        getContentPane().add(cobProd);
        cobProd.setBounds(55, 55, 153, 20);

        botAceptar.setText("Aceptar");
        botAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(botAceptar);
        botAceptar.setBounds(251, 95, 120, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Seleccione el ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 77, 15);

        lblTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 0, 0));
        lblTexto.setText("jLabel2");
        getContentPane().add(lblTexto);
        lblTexto.setBounds(90, 10, 67, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/qwrq.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 410, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JComboBox<String> cobProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCobProd() {
        return cobProd;
    }

    public void setCobProd(JComboBox<String> cobProd) {
        this.cobProd = cobProd;
    }

    public JButton getBotAceptar() {
        return botAceptar;
    }

    public void setBotAceptar(JButton botAceptar) {
        this.botAceptar = botAceptar;
    }

    public JLabel getLblTexto() {
        return lblTexto;
    }

    public void setLblTexto(JLabel lblTexto) {
        this.lblTexto = lblTexto;
    }

}
