/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 * Formulario que permite crear un usuario y establecer sus valores para agregarlo
 * al arreglo de usuarios que interactuaran con el programa
 * @author Andrés Morales
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlTexto = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRUT = new javax.swing.JTextField();
        cmbPeso = new javax.swing.JComboBox<>();
        spnDia = new javax.swing.JSpinner();
        spnMes = new javax.swing.JSpinner();
        spnAnio = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botCrear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menBarra = new javax.swing.JMenuBar();
        MenSalir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(550, 509));
        setPreferredSize(new java.awt.Dimension(550, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("Nombre                               *");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 190, 28);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 153, 0));
        jLabel2.setText("Apellido                               *");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 70, 200, 28);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 153, 0));
        jLabel3.setText("Fecha de Nacimiento        *");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 170, 190, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 153, 0));
        jLabel4.setText("Telefono                              *");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 200, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 0));
        jLabel5.setText("RUT                                      *");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 270, 190, 28);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 153, 0));
        jLabel6.setText("Moneda a utilizar               *");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 330, 190, 27);

        botVolver.setText("Volver");
        botVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botVolver);
        botVolver.setBounds(40, 400, 129, 45);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 0));
        jLabel7.setText("Direccion                            *");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 120, 190, 28);

        pnlTexto.setOpaque(false);
        pnlTexto.setLayout(null);
        pnlTexto.add(txtNombre);
        txtNombre.setBounds(0, 20, 202, 20);
        pnlTexto.add(txtApellido);
        txtApellido.setBounds(0, 60, 202, 20);

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        pnlTexto.add(txtDireccion);
        txtDireccion.setBounds(0, 120, 202, 20);
        pnlTexto.add(txtTelefono);
        txtTelefono.setBounds(0, 220, 202, 20);
        pnlTexto.add(txtRUT);
        txtRUT.setBounds(0, 260, 202, 20);

        cmbPeso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbPeso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Dolar", "Peso Colombiano", "Yen", "Euro" }));
        cmbPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPesoActionPerformed(evt);
            }
        });
        pnlTexto.add(cmbPeso);
        cmbPeso.setBounds(0, 320, 139, 23);

        spnDia.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        spnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        pnlTexto.add(spnDia);
        spnDia.setBounds(0, 170, 63, 20);

        spnMes.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        pnlTexto.add(spnMes);
        spnMes.setBounds(90, 170, 63, 20);

        spnAnio.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        spnAnio.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2017, 1));
        pnlTexto.add(spnAnio);
        spnAnio.setBounds(180, 170, 63, 20);

        getContentPane().add(pnlTexto);
        pnlTexto.setBounds(250, 10, 240, 350);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 153, 0));
        jLabel8.setText("Dia");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 160, 30, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 153, 0));
        jLabel9.setText("Mes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 160, 30, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 153, 0));
        jLabel10.setText("Año");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 160, 27, 17);

        botCrear.setText("Crear");
        botCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearActionPerformed(evt);
            }
        });
        getContentPane().add(botCrear);
        botCrear.setBounds(349, 400, 180, 45);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 0));
        jLabel12.setText("* Campos Obligatorios");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 370, 190, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/qwrq.png"))); // NOI18N
        jLabel11.setText("Campos Obligatorios");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 550, 480);

        MenSalir.setText("Ayuda");
        MenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSalirActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem2);

        jMenuItem1.setText("Quienes Somos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem3);

        menBarra.add(MenSalir);

        setJMenuBar(menBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPesoActionPerformed

    private void botVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botVolverActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void botCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botCrearActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSalirActionPerformed
        System.exit(0);
        JOptionPane.showMessageDialog(rootPane, "Hola");
    }//GEN-LAST:event_MenSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenSalir;
    private javax.swing.JButton botCrear;
    private javax.swing.JButton botVolver;
    private javax.swing.JComboBox<String> cmbPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menBarra;
    private javax.swing.JPanel pnlTexto;
    private javax.swing.JSpinner spnAnio;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUT;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCmbPeso() {
        return cmbPeso;
    }

    public void setCmbPeso(JComboBox<String> cmbPeso) {
        this.cmbPeso = cmbPeso;
    }

    public JTextField getTxtApellido() {
        return txtApellido;
    }

    public void setTxtApellido(JTextField txtApellido) {
        this.txtApellido = txtApellido;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtRUT() {
        return txtRUT;
    }

    public void setTxtRUT(JTextField txtRUT) {
        this.txtRUT = txtRUT;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JButton getBotCrear() {
        return botCrear;
    }

    public void setBotCrear(JButton botCrear) {
        this.botCrear = botCrear;
    }

    public JSpinner getSpnAnio() {
        return spnAnio;
    }

    public void setSpnAnio(JSpinner spnAnio) {
        this.spnAnio = spnAnio;
    }

    public JSpinner getSpnDia() {
        return spnDia;
    }

    public void setSpnDia(JSpinner spnDia) {
        this.spnDia = spnDia;
    }

    public JSpinner getSpnMes() {
        return spnMes;
    }

    public void setSpnMes(JSpinner spnMes) {
        this.spnMes = spnMes;
    }

    public JButton getBotVolver() {
        return botVolver;
    }

    public void setBotVolver(JButton botVolver) {
        this.botVolver = botVolver;
    }

    public JPanel getPnlTexto() {
        return pnlTexto;
    }

    public void setPnlTexto(JPanel pnlTexto) {
        this.pnlTexto = pnlTexto;
    }
    
}
