/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Formulario que permite establecer los datos de las nuevas empresas que se 
 * agregaran al programa
 * @author Andrés Morales
 */
public class CrearEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     */
    public CrearEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        chkAereo = new javax.swing.JCheckBox();
        chkTerrestre = new javax.swing.JCheckBox();
        chkMaritimo = new javax.swing.JCheckBox();
        chkFerreo = new javax.swing.JCheckBox();
        botCrear = new javax.swing.JButton();
        botVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menBarra = new javax.swing.JMenuBar();
        MenSalir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/qwrq.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(560, 485));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Telefono ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 80, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 30, 52, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Metodos de Envio");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 200, 120, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Direccion Web");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 140, 100, 17);

        pnlDatos.setOpaque(false);
        pnlDatos.setLayout(null);
        pnlDatos.add(txtNombre);
        txtNombre.setBounds(20, 10, 210, 20);

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        pnlDatos.add(txtTelefono);
        txtTelefono.setBounds(20, 60, 210, 20);

        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });
        pnlDatos.add(txtURL);
        txtURL.setBounds(20, 120, 210, 20);

        chkAereo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        chkAereo.setForeground(new java.awt.Color(255, 51, 0));
        chkAereo.setText("Aereo");
        chkAereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAereoActionPerformed(evt);
            }
        });
        pnlDatos.add(chkAereo);
        chkAereo.setBounds(40, 210, 110, 30);

        chkTerrestre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        chkTerrestre.setForeground(new java.awt.Color(255, 51, 0));
        chkTerrestre.setText("Terrestre");
        pnlDatos.add(chkTerrestre);
        chkTerrestre.setBounds(40, 240, 110, 30);

        chkMaritimo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        chkMaritimo.setForeground(new java.awt.Color(255, 51, 0));
        chkMaritimo.setText("Maritimo");
        pnlDatos.add(chkMaritimo);
        chkMaritimo.setBounds(40, 270, 110, 30);

        chkFerreo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        chkFerreo.setForeground(new java.awt.Color(255, 51, 0));
        chkFerreo.setText("Ferreo");
        chkFerreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFerreoActionPerformed(evt);
            }
        });
        pnlDatos.add(chkFerreo);
        chkFerreo.setBounds(40, 300, 110, 30);

        getContentPane().add(pnlDatos);
        pnlDatos.setBounds(260, 20, 240, 330);

        botCrear.setText("Crear");
        getContentPane().add(botCrear);
        botCrear.setBounds(370, 370, 150, 40);

        botVolver.setText("Volver");
        getContentPane().add(botVolver);
        botVolver.setBounds(40, 370, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/qwrq.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 430);

        MenSalir.setText("Ayuda");
        MenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSalirActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem2);

        jMenuItem1.setText("Quienes Somos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem3);

        menBarra.add(MenSalir);

        setJMenuBar(menBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSalirActionPerformed
        System.exit(0);
        JOptionPane.showMessageDialog(rootPane, "Hola");
    }//GEN-LAST:event_MenSalirActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void chkAereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAereoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAereoActionPerformed

    private void chkFerreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFerreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFerreoActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenSalir;
    private javax.swing.JButton botCrear;
    private javax.swing.JButton botVolver;
    private javax.swing.JCheckBox chkAereo;
    private javax.swing.JCheckBox chkFerreo;
    private javax.swing.JCheckBox chkMaritimo;
    private javax.swing.JCheckBox chkTerrestre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menBarra;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables

    public JButton getBotCrear() {
        return botCrear;
    }

    public void setBotCrear(JButton botCrear) {
        this.botCrear = botCrear;
    }

    public JButton getBotVolver() {
        return botVolver;
    }

    public void setBotVolver(JButton botVolver) {
        this.botVolver = botVolver;
    }

    public JCheckBox getChkAereo() {
        return chkAereo;
    }

    public void setChkAereo(JCheckBox chkAereo) {
        this.chkAereo = chkAereo;
    }

    public JCheckBox getChkFerreo() {
        return chkFerreo;
    }

    public void setChkFerreo(JCheckBox chkFerreo) {
        this.chkFerreo = chkFerreo;
    }

    public JCheckBox getChkMaritimo() {
        return chkMaritimo;
    }

    public void setChkMaritimo(JCheckBox chkMaritimo) {
        this.chkMaritimo = chkMaritimo;
    }

    public JCheckBox getChkTerrestre() {
        return chkTerrestre;
    }

    public void setChkTerrestre(JCheckBox chkTerrestre) {
        this.chkTerrestre = chkTerrestre;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public void setTxtTelefono(JTextField txtTelefono) {
        this.txtTelefono = txtTelefono;
    }

    public JTextField getTxtURL() {
        return txtURL;
    }

    public void setTxtURL(JTextField txtURL) {
        this.txtURL = txtURL;
    }

    public JPanel getPnlDatos() {
        return pnlDatos;
    }

    public void setPnlDatos(JPanel pnlDatos) {
        this.pnlDatos = pnlDatos;
    }

}
