/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * Formulario que permite interactuar con nuevos productos que el usuario podra importar o no
 * @author Andrés
 */
public class FormProducto extends javax.swing.JFrame {

    /**
     * Creates new form FormProducto
     */
    public FormProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        botSalir = new javax.swing.JButton();
        botVolver = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        botAgregar = new javax.swing.JButton();
        botModificar = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        botImporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menBarra = new javax.swing.JMenuBar();
        MenSalir = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(650, 200, 0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(410, 428));
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 153, 0));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(160, 30, 90, 22);

        botSalir.setText("Salir");
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botSalir);
        botSalir.setBounds(35, 320, 129, 45);

        botVolver.setText("Volver");
        botVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botVolver);
        botVolver.setBounds(247, 320, 129, 45);

        lblNombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(204, 153, 0));
        lblNombre1.setText("Usted esta gestionando los productos a importar de");
        getContentPane().add(lblNombre1);
        lblNombre1.setBounds(20, 0, 480, 30);

        botAgregar.setText("Agregar Producto");
        getContentPane().add(botAgregar);
        botAgregar.setBounds(110, 80, 179, 31);

        botModificar.setText("Modificar Productos Existentes");
        getContentPane().add(botModificar);
        botModificar.setBounds(110, 120, 179, 31);

        botEliminar.setText("Eliminar Producto");
        getContentPane().add(botEliminar);
        botEliminar.setBounds(110, 170, 179, 31);

        botImporte.setText("Productos a Importar");
        getContentPane().add(botImporte);
        botImporte.setBounds(110, 220, 179, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/qwrq.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentX(50.0F);
        jLabel1.setAlignmentY(50.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        MenSalir.setText("Ayuda");
        MenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenSalirActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem2);

        jMenuItem1.setText("Quienes Somos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem1);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenSalir.add(jMenuItem3);

        menBarra.add(MenSalir);

        setJMenuBar(menBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botSalirActionPerformed

    private void botVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botVolverActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenSalirActionPerformed
        System.exit(0);
        JOptionPane.showMessageDialog(rootPane, "Hola");
    }//GEN-LAST:event_MenSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenSalir;
    private javax.swing.JButton botAgregar;
    private javax.swing.JButton botEliminar;
    private javax.swing.JButton botImporte;
    private javax.swing.JButton botModificar;
    private javax.swing.JButton botSalir;
    private javax.swing.JButton botVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JMenuBar menBarra;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JButton getBotSalir() {
        return botSalir;
    }

    public void setBotSalir(JButton botSalir) {
        this.botSalir = botSalir;
    }

    public JButton getBotVolver() {
        return botVolver;
    }

    public void setBotVolver(JButton botVolver) {
        this.botVolver = botVolver;
    }

    public JButton getBotAgregar() {
        return botAgregar;
    }

    public void setBotAgregar(JButton botAgregar) {
        this.botAgregar = botAgregar;
    }

    public JButton getBotEliminar() {
        return botEliminar;
    }

    public void setBotEliminar(JButton botEliminar) {
        this.botEliminar = botEliminar;
    }

    public JButton getBotImporte() {
        return botImporte;
    }

    public void setBotImporte(JButton botImporte) {
        this.botImporte = botImporte;
    }

    public JButton getBotModificar() {
        return botModificar;
    }

    public void setBotModificar(JButton botModificar) {
        this.botModificar = botModificar;
    }


}
